FROM python:3.11-slim

WORKDIR /app

# Installiamo solo le dipendenze di base necessarie
COPY requirements.minimal.txt .
RUN pip install --no-cache-dir -r requirements.minimal.txt

# Copiamo il codice dell'applicazione
COPY app ./app

# Esponiamo la porta
ENV PORT=8080

# Comando per eseguire l'applicazione
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --log-level debug"]
