[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash -c 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}'"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[resource]
cpu = 1
memory = 1024
disk = 2048
