[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.complete"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180  # Mantenuto a 3 minuti
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[scale]
min = 1
max = 2
autoScale = true