[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ultra"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60  # Aumentiamo notevolmente il timeout
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5  # Aumentiamo i tentativi di riavvio

[scale]
min = 1
max = 2
autoScale = true
