[main]
# Configurazione Railway
name = "railway-document-worker"

# Consenti build più lunghe (3 minuti)
max_build_time = 180

# Configurazione del servizio
[service]
# Configura la porta dell'applicazione
internal_port = 8000

# Configurazione dei privilegi
[service.privileged]
enabled = false

# Variabili d'ambiente
[env]
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
MAX_FILE_SIZE_MB = "10"
ENABLE_TABULAR_PROCESSING = "true"
ENABLE_PDF_PROCESSING = "true"
ENABLE_ADVANCED_PDF = "false"
ENABLE_OCR = "true"
ENABLE_IMAGE_PROCESSING = "true"
ENABLE_MISTRAL_VISION = "true"
ENABLE_CLAUDE_FORMAT = "true"
CLAUDE_INCLUDE_RAW_TEXT = "true"
CLAUDE_MAX_RAW_TEXT_LENGTH = "8000"

# Configurazione della salute del servizio
[service.health]
port = 8000
path = "/health"
interval = "30s"
timeout = "5s"
retries = 3
