[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.unified"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120  # Aumentiamo il timeout a 2 minuti
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10  # Aumentiamo i tentativi di riavvio

[scale]
min = 1
max = 2
autoScale = true